+ add timestamps in the log/note/subnote/die functions

diff --git a/pyhail-spark b/pyhail-spark
--- a/pyhail-spark
+++ b/pyhail-spark
@@ -1,6 +1,6 @@
 #!/bin/bash
 
-__VERSION__=0.4.1
+__VERSION__=0.5.0
 
 # Example cluster mode invocation
 # bsub -q long \
@@ -49,21 +49,25 @@ export PYSPARK_PYTHON=/gscuser/idas/.pyenv/versions/2.7.10/bin/python
 # set +o xtrace
 
 function log {
-    echo "==== $@ ====" >&2
+    local timestamp=$(date +"%Y-%m-%d %T")
+    echo "==== [ ${timestamp} ] $@ ====" >&2
 }
 
 function note {
-    echo "---> $@" >&2
+    local timestamp=$(date +"%Y-%m-%d %T")
+    echo "---> [ ${timestamp} ] $@" >&2
 }
 
 function subnote {
     local msg=$1
-    echo "--->> $@" >&2
+    local timestamp=$(date +"%Y-%m-%d %T")
+    echo "--->> [ ${timestamp} ] $@" >&2
 }
 
 function die {
-    echo "ERROR: $@" >&2
-    exit 1
+    local timestamp=$(date +"%Y-%m-%d %T")
+    echo "[ ${timestamp} ] ERROR: $@" >&2
+    kill -s TERM ${TOP_PID}
 }
 
 function ensure_spark_log_dir {
@@ -196,7 +200,7 @@ function run_pyhail_cmd {
     local pyspark=${spark_python_libs}/pyspark.zip
     local pyhail=${hail_python_libs}/pyhail.zip
 
-    note "(Hail Command) Start Time:" $(date +"%Y-%m-%d %T")
+    note "(Hail Command) Start"
     set -o xtrace
     ${SPARK_HOME}/bin/spark-submit \
         --jars ${SPARK_HAIL_JAR} \
@@ -204,8 +208,7 @@ function run_pyhail_cmd {
         --master spark://$SPARK_MASTER:$SPARK_MASTER_PORT \
         $@
     set +o xtrace
-    note "(Hail Command) Finish Time:" $(date +"%Y-%m-%d %T")
-
+    note "(Hail Command) Finish"
 }
 
 function cluster {
